package com.apicatalog.jsonld;

/**
 * The {@link JsonLdErrorCode} represents the collection of valid JSON-LD error
 * codes.
 * 
 * @see <a href=
 *      "https://www.w3.org/TR/json-ld11-api/#jsonlderrorcode">JsonLdErrorCode
 *      Specification</a>
 * 
 */
public enum JsonLdErrorCode {

	/**
	 * Two <a href="https://www.w3.org/TR/rdf11-concepts/#dfn-property">properties</a>
	 * which expand to the same keyword have been detected. This might occur if a
	 * keyword and an alias thereof are used at the same time.
	 */
	COLLIDING_KEYWORDS,
	/**
	 * Multiple conflicting indexes have been found for the same node.
	 */
	CONFLICTING_INDEXES,
	/**
	 * Maximum number of <code>@context</code> URLs exceeded.
	 */
	CONTEXT_OVERFLOW, 
	/**
	 * A cycle in IRI mappings has been detected.
	 */
	CYCLIC_IRI_MAPPING, 
	
	INVALID_KEYWORD_ID_VALUE, INVALID_KEYWORD_IMPORT_VALUE,
	INVALID_KEYWORD_INCLUDED_VALUE, INVALID_KEYWORD_INDEX_VALUE, INVALID_KEYWORD_NEST_VALUE,
	INVALID_KEYWORD_PREFIX_VALUE, INVALID_KEYWORD_PROPAGATE_VALUE, INVALID_KEYWORD_PROTECTED_VALUE,
	INVALID_KEYWORD_REVERSE_VALUE, INVALID_KEYWORD_VERSION_VALUE, INVALID_BASE_DIRECTION, INVALID_BASE_IRI,
	INVALID_CONTAINER_MAPPING, INVALID_CONTEXT_ENTRY, INVALID_CONTEXT_NULLIFICATION, INVALID_DEFAULT_LANGUAGE,
	INVALID_IRI_MAPPING, INVALID_JSON_LITERAL, INVALID_KEYWORD_ALIAS, INVALID_LANGUAGE_MAP_VALUE,
	INVALID_LANGUAGE_MAPPING, INVALID_LANGUAGE_TAGGED_STRING, INVALID_LANGUAGE_TAGGED_VALUE, INVALID_LOCAL_CONTEXT,
	INVALID_REMOTE_CONTEXT, INVALID_REVERSE_PROPERTY_MAP, INVALID_REVERSE_PROPERTY_VALUE, INVALID_REVERSE_PROPERTY,
	INVALID_SCOPED_CONTEXT, INVALID_SCRIPT_ELEMENT, INVALID_SET_OR_LIST_OBJECT, INVALID_TERM_DEFINITION,
	INVALID_TYPE_MAPPING, INVALID_TYPE_VALUE, INVALID_TYPED_VALUE, INVALID_VALUE_OBJECT_VALUE, INVALID_VALUE_OBJECT,
	INVALID_VOCAB_MAPPING, IRI_CONFUSED_WITH_PREFIX, KEYWORD_REDEFINITION, LOADING_DOCUMENT_FAILED,
	LOADING_REMOTE_CONTEXT_FAILED, MULTIPLE_CONTEXT_LINK_HEADERS, PROCESSING_MODE_CONFLICT, PROTECTED_TERM_REDEFINITION
}
