name: Publish JRE17 to the Maven Central

on:
  release:
    types: [created]
    
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: maven-central
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_TOKEN_ID
          server-password: CENTRAL_TOKEN_SECRET
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build and Deploy
        run: mvn -B -Pmaven-central deploy
        env:
          CENTRAL_TOKEN_ID: ${{ secrets.CENTRAL_TOKEN_ID }}
          CENTRAL_TOKEN_SECRET: ${{ secrets.CENTRAL_TOKEN_SECRET }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GNUPGHOME: ${{ env.GNUPGHOME }}

